{"url":"https://api.github.com/repos/willmcgugan/rich/issues/317","repository_url":"https://api.github.com/repos/willmcgugan/rich","labels_url":"https://api.github.com/repos/willmcgugan/rich/issues/317/labels{/name}","comments_url":"https://api.github.com/repos/willmcgugan/rich/issues/317/comments","events_url":"https://api.github.com/repos/willmcgugan/rich/issues/317/events","html_url":"https://github.com/willmcgugan/rich/issues/317","id":712744009,"node_id":"MDU6SXNzdWU3MTI3NDQwMDk=","number":317,"title":"[BUG] Rich is incompatible with pytest capsys fixture","user":{"login":"ssbarnea","id":102495,"node_id":"MDQ6VXNlcjEwMjQ5NQ==","avatar_url":"https://avatars3.githubusercontent.com/u/102495?v=4","gravatar_id":"","url":"https://api.github.com/users/ssbarnea","html_url":"https://github.com/ssbarnea","followers_url":"https://api.github.com/users/ssbarnea/followers","following_url":"https://api.github.com/users/ssbarnea/following{/other_user}","gists_url":"https://api.github.com/users/ssbarnea/gists{/gist_id}","starred_url":"https://api.github.com/users/ssbarnea/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ssbarnea/subscriptions","organizations_url":"https://api.github.com/users/ssbarnea/orgs","repos_url":"https://api.github.com/users/ssbarnea/repos","events_url":"https://api.github.com/users/ssbarnea/events{/privacy}","received_events_url":"https://api.github.com/users/ssbarnea/received_events","type":"User","site_admin":false},"labels":[{"id":1668492283,"node_id":"MDU6TGFiZWwxNjY4NDkyMjgz","url":"https://api.github.com/repos/willmcgugan/rich/labels/question","name":"question","color":"d876e3","default":true,"description":"Further information is requested"}],"state":"closed","locked":false,"assignee":{"login":"ssbarnea","id":102495,"node_id":"MDQ6VXNlcjEwMjQ5NQ==","avatar_url":"https://avatars3.githubusercontent.com/u/102495?v=4","gravatar_id":"","url":"https://api.github.com/users/ssbarnea","html_url":"https://github.com/ssbarnea","followers_url":"https://api.github.com/users/ssbarnea/followers","following_url":"https://api.github.com/users/ssbarnea/following{/other_user}","gists_url":"https://api.github.com/users/ssbarnea/gists{/gist_id}","starred_url":"https://api.github.com/users/ssbarnea/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ssbarnea/subscriptions","organizations_url":"https://api.github.com/users/ssbarnea/orgs","repos_url":"https://api.github.com/users/ssbarnea/repos","events_url":"https://api.github.com/users/ssbarnea/events{/privacy}","received_events_url":"https://api.github.com/users/ssbarnea/received_events","type":"User","site_admin":false},"assignees":[{"login":"ssbarnea","id":102495,"node_id":"MDQ6VXNlcjEwMjQ5NQ==","avatar_url":"https://avatars3.githubusercontent.com/u/102495?v=4","gravatar_id":"","url":"https://api.github.com/users/ssbarnea","html_url":"https://github.com/ssbarnea","followers_url":"https://api.github.com/users/ssbarnea/followers","following_url":"https://api.github.com/users/ssbarnea/following{/other_user}","gists_url":"https://api.github.com/users/ssbarnea/gists{/gist_id}","starred_url":"https://api.github.com/users/ssbarnea/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ssbarnea/subscriptions","organizations_url":"https://api.github.com/users/ssbarnea/orgs","repos_url":"https://api.github.com/users/ssbarnea/repos","events_url":"https://api.github.com/users/ssbarnea/events{/privacy}","received_events_url":"https://api.github.com/users/ssbarnea/received_events","type":"User","site_admin":false}],"milestone":null,"comments":2,"created_at":"2020-10-01T11:14:47Z","updated_at":"2020-10-08T07:36:14Z","closed_at":"2020-10-08T07:36:14Z","author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"**Describe the bug**\r\nAdopters of rich will eventually discover that their use of [capsys](https://docs.pytest.org/en/stable/capture.html) in pytest unittest gets broken when they integrate the library.\r\n\r\nWhile this is somehow expected we should document a recipe for adapting testing in such way that does not break when using rich.\r\n\r\nExample test:\r\n\r\n```\r\nimport pytest\r\n\r\ndef test_output(capsys):\r\n \tfoo() # expected to produce stdout content\r\n\tstdout, stderr = capsys.readouterr()\r\n\tassert stdout == \"...\"\r\n\tassert stderr == \"...\"\r\n```\r\n\r\nThis has repercussions even for logging functions and I even encountered errors when parametrizing tests like `ValueError: I/O operation on closed file.` which are caused by Console() instance being closed after the first test.\r\n\r\nAs rich itself makes use of pytest it should not be a big deal to include an example.","closed_by":{"login":"willmcgugan","id":554369,"node_id":"MDQ6VXNlcjU1NDM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/554369?v=4","gravatar_id":"","url":"https://api.github.com/users/willmcgugan","html_url":"https://github.com/willmcgugan","followers_url":"https://api.github.com/users/willmcgugan/followers","following_url":"https://api.github.com/users/willmcgugan/following{/other_user}","gists_url":"https://api.github.com/users/willmcgugan/gists{/gist_id}","starred_url":"https://api.github.com/users/willmcgugan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/willmcgugan/subscriptions","organizations_url":"https://api.github.com/users/willmcgugan/orgs","repos_url":"https://api.github.com/users/willmcgugan/repos","events_url":"https://api.github.com/users/willmcgugan/events{/privacy}","received_events_url":"https://api.github.com/users/willmcgugan/received_events","type":"User","site_admin":false},"performed_via_github_app":null}